(prelude-require-packages '(
                            color-theme-sanityinc-tomorrow
                            dash-at-point
                            avy-zap
                            ace-isearch
                            ag
                            dumb-jump
                            projector
                            rspec-mode
                            emmet-mode
                            mode-icons
                            helm-swoop
                            writeroom-mode
                            js2-refactor
                            emojify
                            bbdb
                            prettier-js
                            magit-gh-pulls
                            default-text-scale
                            ))
